[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"
  # Skip secrets scanning for build output
  SECRETS_SCAN_ENABLED = "false"
  # Prisma configuration
  PRISMA_CLI_BINARY_TARGETS = "rhel-openssl-3.0.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"
